Repository coding-union-kr/haru-puppy, pull requests merged in 2023-12, with the labels that each got.

#6 design: WalkRank 컴포넌트 디자인 #4
  front/.prettierrc
  front/app/components/chart/WalkRank.tsx
  front/app/globals.css
  front/app/layout.tsx
  front/app/page.module.css
  front/package-lock.json
  front/package.json
  front/styles/styled.d.ts
  front/styles/theme.ts
Labels: FE, 🎨Design

#7 design: Button 컴포넌트 UI 작성 및 globals.css 수정 #3
  front/app/components/button/Button.tsx
  front/app/globals.css
Labels: FE, 🎨Design

#10 design: BottomNavigation 컴포넌트 UI 작성 및 mui/icons-material 설치 #3
  front/app/components/navigation/BottomNavigation.tsx
  front/app/components/navigation/BottomNavigationIcon.tsx
  front/next.config.js
  front/package-lock.json
  front/package.json
Labels: FE, 🎨Design

#11 컴포넌트 개발
  front/app/components/card/ReportCard.tsx
  front/app/components/card/TodoCard.tsx
  front/app/components/chart/WalkRank.tsx
  front/app/components/profile/MateProfile.tsx
  front/app/components/profile/UserProfile.tsx
Labels: FE, 🎨Design

#12 design: TopNavigation UI 작성
  front/app/components/navigation/TopNavigation.tsx
  front/public/svgs/notifications_unread.svg
Labels: FE, 🎨Design

#14 design: NavMenu, Input, 카카오버튼으로 시작하기 컴포넌트 UI 작성
  front/app/(route)/auth/page.tsx
  front/app/(route)/setting/components/NavMenu.tsx
  front/app/components/input/Input.tsx
  front/public/svgs/message-circle.svg
Labels: FE, 🎨Design

#15 Feat: User, Dog, Home 엔티티 생성
  back/build.gradle
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/DogGender.java
  back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/UserRole.java
  back/src/main/java/com/developaw/harupuppy/domain/user/repository/UserRepository.java
  back/src/main/resources/application-develop.yml
Labels: ✨ Feature, BE

#17 feat: 스케줄 관련 엔티티 구현
  .github/workflows/BackEnd-CI.yml
  back/build.gradle
  back/gradle/wrapper/gradle-wrapper.jar
  back/gradle/wrapper/gradle-wrapper.properties
  back/gradlew
  back/gradlew.bat
  back/src/main/java/com/developaw/harupuppy/domain/activity/domain/Activity.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/DogGender.java
  back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
  back/src/main/java/com/developaw/harupuppy/domain/notification/domain/Notification.java
  back/src/main/java/com/developaw/harupuppy/domain/notification/domain/NotificationType.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/AlertType.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/RepeatType.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/Schedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/ScheduleType.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/UserSchedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/UserSchedulePK.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/global/common/DateEntity.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/JpaAuditingConfig.java
  back/src/main/resources/application-develop.yml
  back/src/main/resources/application-prod.yml
  back/src/main/resources/application.yml
  back/src/test/java/com/developaw/harupuppy/HarupuppyApplicationTests.java
Labels: ✨ Feature

#22 Design: Calendar 컴포넌트와 global.css 수정
  front/app/components/card/TodoCard.tsx
  front/app/components/schedule/calendar.tsx
  front/app/globals.css
Labels: FE, 🎨Design

#25 design: layout 반응형
  front/app/components/layout/layout.tsx
  front/app/components/navigation/BottomNavigation.tsx
  front/app/components/navigation/TopNavigation.tsx
Labels: FE, 🎨Design

#26 design: 일정추가 모달 관련 컴포넌트들 UI 작성
  front/app/(route)/schedule/components/DateDropdown.tsx
  front/app/(route)/schedule/components/MateSelect.tsx
  front/app/(route)/schedule/components/NotiDropdown.tsx
  front/app/(route)/schedule/components/RepeatDropdown.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/(route)/schedule/components/ScheduleTypeDropdown.tsx
  front/app/(route)/schedule/components/Select.tsx
  front/app/(route)/schedule/components/TimeDropdown.tsx
  front/package-lock.json
  front/package.json
  front/public/svgs/close.svg
  front/public/svgs/close_grey.svg
  front/public/svgs/cover-box.svg
  front/public/svgs/dentistry.svg
  front/public/svgs/food.svg
  front/public/svgs/pet_supplies.svg
  front/public/svgs/poop.svg
Labels: FE, 🎨Design

#31 design: TopNavigation 수정
  front/app/components/layout/layout.tsx
  front/app/components/navigation/TopNavigation.tsx
Labels: FE, 🎨Design

#29 design: MateProfile 컴포넌트와 UserProfile 수정
  front/app/(route)/schedule/components/MateSelect.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/components/profile/MateProfile.tsx
  front/app/components/profile/UserProfile.tsx
  front/public/svgs/mate_check.svg
Labels: ✨ Feature, FE, 🎨Design

#33 design: 회원가입 페이지 UI 작성 및 Input enum 추가
  front/app/(route)/auth/page.tsx
  front/app/(route)/auth/signup/page.tsx
  front/app/components/input/Input.tsx
  front/public/svgs/message-circle.svg
Labels: ✨ Feature, FE, 🎨Design

#27 feat: 스케줄 CRUD API 구현
  back/src/main/java/com/developaw/harupuppy/domain/schedule/api/ScheduleController.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/application/ScheduleService.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dao/ScheduleRepository.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/RepeatType.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/Schedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/UserSchedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/request/ScheduleCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/request/ScheduleUpdateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/response/ScheduleResponse.java
  back/src/main/java/com/developaw/harupuppy/global/common/response/Response.java
  back/src/test/java/com/developaw/harupuppy/domain/schedule/api/ScheduleControllerTest.java
  back/src/test/java/com/developaw/harupuppy/domain/schedule/application/ScheduleServiceTest.java
  back/src/test/java/com/developaw/harupuppy/domain/schedule/dao/ScheduleRepositoryTest.java
  back/src/test/java/com/developaw/harupuppy/fixture/ScheduleFixture.java
Labels: ✨ Feature, BE, ✅ Test

#37 fix: 스케줄 목록 조회를 홈 단위로 하기
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
  back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/api/ScheduleController.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/application/ScheduleService.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dao/ScheduleRepository.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/Schedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/request/ScheduleCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/response/ScheduleResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/test/java/com/developaw/harupuppy/domain/schedule/application/ScheduleServiceTest.java
  back/src/test/java/com/developaw/harupuppy/domain/schedule/dao/ScheduleRepositoryTest.java
  back/src/test/java/com/developaw/harupuppy/fixture/ScheduleFixture.java
Labels: BE, 🐞 Bug

#38 design: 강아지 등록 페이지(Input, GenderSelect, DateDropdown, Button)
  front/app/(route)/profile/dog/components/GenderSelect.tsx
  front/app/(route)/profile/dog/page.tsx
  front/app/(route)/schedule/components/DateDropdown.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/components/input/Input.tsx
Labels: ✨ Feature, FE, 🎨Design

#40 design: 유저 프로필 등록 페이지 (RoleDropdown, ProfileImg)
  front/app/(route)/profile/my/components/RoleDropdown.tsx
  front/app/(route)/profile/my/page.tsx
  front/app/components/profile/ProfileImg.tsx
  front/public/svgs/dog_profile.svg
  front/public/svgs/editable.svg
  front/public/svgs/user_profile.svg
Labels: ✨ Feature, FE, 🎨Design

#43 fix: TopNav token 없을 때 뒤로가기 버튼 숨기기
  front/app/components/navigation/TopNavigation.tsx
Labels: FE, 🐞 Bug, 🎨Design

#44 fix: MateList 컴포넌트 수정과 Home 화면 구성
  front/app/(route)/schedule/components/MateSelect.tsx
  front/app/(route)/schedule/page.tsx
  front/app/components/card/ReportCard.tsx
  front/app/components/chart/WalkRank.tsx
  front/app/components/home/MateList.tsx
  front/app/components/home/UserProfile.tsx
  front/app/components/profile/MateProfile.tsx
  front/app/components/profile/UserProfile.tsx
  front/app/page.tsx
  front/public/svgs/dog_bath.svg
  front/public/svgs/dog_health_check.svg
  front/public/svgs/home_edit_btn.svg
  front/public/svgs/home_edit_close_btn.svg
  front/public/svgs/mate_plus.svg
  front/public/svgs/paw.svg
Labels: ✨ Feature, FE, 🎨Design

#47 fix: 강아지 프로필 formData birthday 수정 #45
  front/app/(route)/profile/dog/page.tsx
Labels: ✨ Feature, FE, 🐞 Bug

#50 fix: ScheduleAdd 컴포넌트 추가 수정
  front/app/(route)/schedule/components/DateDropdown.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/(route)/schedule/components/ScheduleTypeDropdown.tsx
  front/app/components/input/MemoTextArea.tsx
  front/app/globals.css
Labels: ✨ Feature, FE, 🐞 Bug

#52 design: 로그인 페이지 복구
  front/app/(route)/auth/page.tsx
  front/app/(route)/auth/signup/page.tsx
  front/app/components/layout/layout.tsx
  front/public/svgs/message-circle.svg
Labels: ✨ Feature, FE, 🎨Design

#58 fix: ConainerLayout에서 네비게이션들 삭제 #57
  front/app/components/layout/layout.tsx
Labels: FE, 🐞 Bug, 🎨Design

#60 fix: Input 및 드롭다운 기본값 문제 검토
  front/app/(route)/profile/my/components/RoleDropdown.tsx
  front/app/(route)/profile/my/page.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/(route)/schedule/components/ScheduleTypeDropdown.tsx
  front/app/components/input/Input.tsx
  front/app/config/scheduleTypeOptions.tsx
Labels: FE, 🐞 Bug, 🎨Design

#63 feat: 강아지 프로필 등록에 ProfileImg 컴포넌트 추가
  front/app/(route)/profile/dog/page.tsx
  front/app/components/profile/ProfileImg.tsx
Labels: ✨ Feature, FE

#62 feat: oAuth 로그인 로직과 회원가입 페이지
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/(route)/auth/login/page.tsx
  front/app/(route)/auth/userprofile/page.tsx
  front/app/(route)/auth/welcome/page.tsx
  front/app/components/navigation/TopNavigation.tsx
  front/app/constants/auth.ts
  front/package-lock.json
  front/package.json
  front/public/svgs/dog-logo.svg
Labels: ✨ Feature, FE

#65 fix: 카카오 로그인 백엔드 요청 url 변수와 코드 수정
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/constants/auth.ts
  front/next.config.js
Labels: FE, 🐞 Bug

#67 feat: 메이트 초대하기 기본 기능 연결
  front/app/(route)/invite/page.tsx
  front/app/components/navigation/TopNavigation.tsx
  front/app/layout.tsx
  front/global.d.ts
  front/public/svgs/kakao_logo.svg
Labels: ✨ Feature, FE
