Repository coding-union-kr/haru-puppy, pull requests merged in 2024-01, with the labels that each got.

#77 design: 알림 페이지 UI 작성
  front/app/(route)/noti/components/NotiCard.tsx
  front/app/(route)/noti/components/NotiCardGroup.tsx
  front/app/(route)/noti/page.tsx
  front/app/(route)/schedule/components/ScheduleTypeDropdown.tsx
  front/app/components/navigation/TopNavigation.tsx
  front/app/constants/scheduleTypeOptions.tsx
Labels: ✨ Feature, FE, 🎨Design

#80 feat: 알림 설정용 ToggleSwitch 컴포넌트 작성 및 NavMenu에 children prop 추가
  front/app/(route)/setting/components/NavMenu.tsx
  front/app/components/toggle/ToggleSwitch.tsx
Labels: ✨ Feature, FE, 🎨Design

#72 fix: 카카오 로그인 분기처리 수정 #70
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/components/card/ReportCard.tsx
  front/app/components/home/MateList.tsx
  front/app/components/navigation/BottomNavigation.tsx
  front/app/components/navigation/TopNavigation.tsx
  front/app/components/profile/MateProfile.tsx
  front/app/page.tsx
Labels: ✨ Feature, FE, 🐞 Bug

#68 인증 필터 구현 및 OAuth2 로그인 기능 구현
  back/build.gradle
  back/src/main/java/com/developaw/harupuppy/domain/activity/domain/Activity.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
  back/src/main/java/com/developaw/harupuppy/domain/user/api/AuthController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/api/UserController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/OAuthService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/RedisService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserFacadeService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/Home.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/UserDetail.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/TokenDto.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/LoginResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/OAuthLoginResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/OAuthTokenResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/UserDetailResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/repository/UserRepository.java
  back/src/main/java/com/developaw/harupuppy/global/common/response/Response.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/AuthenticationConfig.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/PasswordEncoder.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/filter/AuthenticationFilter.java
  back/src/main/java/com/developaw/harupuppy/global/utils/DateUtils.java
  back/src/main/java/com/developaw/harupuppy/global/utils/JwtTokenUtils.java
  back/src/main/resources/application-develop.yml
Labels: ✨ Feature, BE

#73 유저 회원가입 API 구현
  back/build.gradle
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/domain/DogGender.java
  back/src/main/java/com/developaw/harupuppy/domain/dog/repository/DogRepository.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/domain/Schedule.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/ScheduleCreateDto.java
  back/src/main/java/com/developaw/harupuppy/domain/schedule/dto/request/ScheduleCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/api/AuthController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/api/UserController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserFacadeService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/UserRole.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/request/DogCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/request/HomeCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/request/UserCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/DogDetailResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/HomeDetailResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/UserCreateResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/UserDetailResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/repository/HomeRepository.java
  back/src/main/java/com/developaw/harupuppy/global/common/response/Response.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/AuthenticationConfig.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/RedisConfig.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/filter/AuthenticationFilter.java
  back/src/main/java/com/developaw/harupuppy/global/utils/JwtTokenUtils.java
  back/src/main/java/com/developaw/harupuppy/global/utils/KoreanNickNameValidator.java
  back/src/main/java/com/developaw/harupuppy/global/utils/KoreanNickname.java
  back/src/main/resources/application-develop.yml
  back/src/test/java/com/developaw/harupuppy/domain/schedule/api/ScheduleControllerTest.java
Labels: ✨ Feature, BE

#87 fix: 헤더 추가& response 객체 수정 #86
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/_utils/apis/interceptors.tsx
Labels: ✨ Feature, FE, 🐞 Bug

#94 fix: CORS 에러 리다이렉트 페이지 로직과 백엔드 URL 변수 수정
  .DS_Store
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/constants/auth.ts
  front/app/layout.tsx
  front/next.config.js
Labels: ✨ Feature, FE, 🐞 Bug

#93 fix: CORS 설정 추가 및 OAuth 이메일 파싱 수정
  back/src/main/java/com/developaw/harupuppy/domain/user/api/AuthController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/OAuthService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserFacadeService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/OAuthTokenResponse.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/AuthenticationConfig.java
Labels: BE, 🐞 Bug

#96 feat: 회원가입 POST API 요청
  front/app/(route)/auth/register/dog/page.tsx
  front/app/(route)/auth/register/user/page.tsx
  front/app/(route)/auth/userprofile/page.tsx
  front/app/(route)/auth/welcome/page.tsx
  front/app/(route)/profile/dog/components/GenderSelect.tsx
  front/app/(route)/profile/my/components/RoleDropdown.tsx
  front/app/components/input/Input.tsx
  front/app/components/navigation/TopNavigation.tsx
  front/app/constants/auth.ts
  front/app/interfaces/Dog.ts
  front/app/interfaces/User.ts
Labels: ✨ Feature, FE

#74 Feat/53 회원정보수정
  back/src/main/java/com/developaw/harupuppy/domain/user/api/UserController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/UserRole.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/UserResponse.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/UserUpdateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/repository/UserRepository.java
  back/src/main/java/com/developaw/harupuppy/global/common/exception/ExceptionControllerAdvice.java
  back/src/main/java/com/developaw/harupuppy/global/common/response/Response.java
  back/src/test/java/com/developaw/harupuppy/fixture/ScheduleFixture.java
Labels: ✨ Feature, BE

#101 fix: birthday 초기값 설정 및 회원가입 POST 요청 두번 날라가는 문제 확인 위해 console.log 조정 #99
  front/app/(route)/auth/register/dog/page.tsx
Labels: FE, 🐞 Bug

#84 fix: 캘린더 컴포넌트 분리와 디자인 수정
  front/app/(route)/schedule/components/DateDropdown.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/(route)/schedule/page.tsx
  front/app/components/card/TodoCard.tsx
  front/app/components/schedule/FullCalendar.tsx
  front/app/components/schedule/WeekCalendar.tsx
  front/app/globals.css
  front/app/page.tsx
  front/public/svgs/add_circle.svg
Labels: ✨ Feature, FE

#103 refactor: 컴포넌트 및 폴더 구조 정리
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/(route)/auth/login/page.tsx
  front/app/(route)/auth/register/dog/page.tsx
  front/app/(route)/auth/register/user/page.tsx
  front/app/(route)/auth/welcome/page.tsx
  front/app/(route)/home/components/MateList.tsx
  front/app/(route)/home/components/ReportCard.tsx
  front/app/(route)/home/components/UserProfile.tsx
  front/app/(route)/home/components/WalkRank.tsx
  front/app/(route)/home/page.tsx
  front/app/(route)/profile/dog/page.tsx
  front/app/(route)/schedule/components/ScheduleAdd.tsx
  front/app/(route)/schedule/page.tsx
  front/app/_types/schedule/Schedule.ts
  front/app/_types/user/Dog.ts
  front/app/_types/user/User.ts
  front/app/api/hello/route.ts
  front/app/components/card/TodoCard.tsx
  front/app/components/profile/DateDropdown.tsx
  front/app/components/profile/GenderSelect.tsx
  front/app/components/profile/RoleDropdown.tsx
  front/app/components/profile/UserProfile.tsx
  front/app/components/schedule/FullCalendar.tsx
  front/app/constants/api.ts
  front/app/page.tsx
  front/package-lock.json
  front/package.json
Labels: FE, 🔨 Refactor

#98 design: 설정 페이지 UI와 유저 수정 페이지 연결
  front/app/(route)/profile/my/page.tsx
  front/app/(route)/setting/components/NavMenu.tsx
  front/app/(route)/setting/components/UpperUserProfile.tsx
  front/app/(route)/setting/page.tsx
  front/app/components/modal/modal.tsx
  front/app/components/navigation/TopNavigation.tsx
Labels: ✨ Feature, FE, 🎨Design

#90 feat: 로그아웃, 토큰재발행, 유저탈퇴 기능 구현
  back/src/main/java/com/developaw/harupuppy/domain/user/api/AuthController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/api/UserController.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/RedisService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserFacadeService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/application/UserService.java
  back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/TokenDto.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/request/UserCreateRequest.java
  back/src/main/java/com/developaw/harupuppy/domain/user/dto/response/UserDetailResponse.java
  back/src/main/java/com/developaw/harupuppy/global/common/response/Response.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/AuthenticationConfig.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/PasswordEncoder.java
  back/src/main/java/com/developaw/harupuppy/global/configuration/filter/AuthenticationFilter.java
  back/src/main/java/com/developaw/harupuppy/global/utils/JwtTokenUtils.java
Labels: ✨ Feature, BE

#107 feat: 시작 페이지 라우트 token유무에 따라 다르게 주기 #106
  front/app/page.tsx
Labels: ✨ Feature, FE

#105 refactor: 스케줄 추가 컴포넌트 내 select, dropdown 리팩토링
  front/app/(route)/auth/register/dog/page.tsx
  front/app/(route)/home/components/MateList.tsx
  front/app/(route)/profile/dog/page.tsx
  front/app/(route)/schedule/components/MateSelect.tsx
  front/app/(route)/schedule/components/NotiDropdown.tsx
  front/app/(route)/schedule/components/NotiSelect.tsx
  front/app/(route)/schedule/components/RepeatDropdown.tsx
  front/app/(route)/schedule/components/RepeatSelect.tsx
  front/app/(route)/schedule/components/ScheduleAddForm.tsx
  front/app/(route)/schedule/components/ScheduleTypeSelect.tsx
  front/app/(route)/schedule/components/TextDropdown.tsx
  front/app/(route)/schedule/components/TimeSelect.tsx
  front/app/(route)/schedule/page.tsx
  front/app/components/profile/DateSelect.tsx
  front/app/components/profile/MateProfile.tsx
Labels: FE, 🔨 Refactor

#113 feat: 유저 프로필 수정 API 요청
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/(route)/auth/register/dog/page.tsx
  front/app/(route)/profile/my/page.tsx
  front/app/_hooks/usePersistentRecoilState.ts
  front/app/_states/userState.ts
  front/app/components/button/Button.tsx
  front/app/components/input/Input.tsx
  front/app/components/modal/modal.tsx
  front/app/components/profile/RoleDropdown.tsx
  front/app/layout.tsx
  front/global.d.ts
  front/package-lock.json
  front/package.json
Labels: ✨ Feature, FE

#112 design: 로딩스피너 컴포넌트 추가 & 로그인 콜백 페이지에 적용 #109
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/components/loading/loading.tsx
  front/public/svgs/loading.gif
Labels: ✨ Feature, FE, 🎨Design

#118 refactor: recoil-persist로 recoil 전역상태 관리
  front/app/(route)/auth/callback/kakao/page.tsx
  front/app/(route)/auth/register/dog/page.tsx
  front/app/(route)/profile/my/page.tsx
  front/app/_hooks/usePersistentRecoilState.ts
  front/app/_states/userState.ts
  front/app/constants/api.ts
  front/package-lock.json
  front/package.json
Labels: FE, 🐞 Bug, 🔨 Refactor
