Repository coding-union-kr/haru-puppy, pull requests merged in 2024-02, with the labels that each got.

#123 feat: 홈 & 스케줄 api 요청 수정 #122
  front/app/(route)/home/page.tsx
  front/app/components/schedule/FullCalendar.tsx
Labels: ✨ Feature, FE

#120 feat: 리프레시 토큰 axios interceptor #116
  front/app/(route)/setting/page.tsx
  front/app/_utils/apis/interceptors.tsx
Labels: ✨ Feature, FE

#124 feat: 초대받은 유저 회원가입 POST API 요청
  front/app/(route)/auth/login/page.tsx
  front/app/(route)/auth/register/user/page.tsx
  front/app/(route)/invite/page.tsx
  front/app/_states/userState.ts
Labels: ✨ Feature, FE, 🔨 Refactor

#126 fix: Invalid hook call 에러
  front/app/(route)/auth/login/page.tsx
Labels: ✨ Feature, FE, 🐞 Bug
